# Generated by Django 3.2.7 on 2023-03-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
